version: "3.9"
services:

  httpd:
    image: httpd:2.4.51
    ports:
      - "8080:80"

  inspec-sidecar:
    depends_on:
      - httpd
    build:
      context: .
      dockerfile: Dockerfile-Inspec
    volumes:
      - $PWD:/share
      - /var/run/docker.sock:/var/run/docker.sock
