# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  # Need this block for Vagrant/VirtualBox issues
  config.vm.provider "virtualbox" do |v|
    v.gui = true
  end
  
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update

    # Docker Engine
    # https://docs.docker.com/engine/install/ubuntu/
    sudo apt-get update
    sudo apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    sudo apt-key fingerprint 0EBFCD88
    sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    sudo apt-get update
    sudo apt-get install -y docker-ce docker-ce-cli containerd.io

    # Cosign binary
    curl -LO https://github.com/sigstore/cosign/releases/download/v1.3.1/cosign-linux-amd64
    chmod +x cosign-linux-amd64
    sudo mv cosign-linux-amd64 /usr/local/bin/cosign
  SHELL
end
